// <auto-generated />
namespace NailsApp.Data.MigrationIdentity
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FirstIdentityMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FirstIdentityMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201510091008562_FirstIdentityMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
